import Head from "next/head";
import { useState } from "react";
import {
  BsFillMoonStarsFill,
  BsFillSunFill,
  BsFillArrowDownCircleFill,
} from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import aymericPic from "../public/aymericPic.png";
import kasaPic from "../public/MiniatureKasa.png";
import contractGeneratorPic from "../public/MiniatureOutilContrat.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Di Maggio Aymeric Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" font-Syne bg-white px-10 md:px-20 2xl:px-60 transition-colors  dark:bg-gray-900 fade-in">
        <section className="min-h-screen ">
          <nav className="py-8 mb-2 flex justify-between items-center fade-in">
            <h1 className="text-lg text-emerald-500 font-medium dark:text-white">
              <a href="#" className="hover:text-emerald-500">
                Aymeric Di Maggio
              </a>
            </h1>
            <div className="flex justify-between items-center">
              {darkMode ? (
                <div className="flex items-center">
                  <BsFillMoonStarsFill
                    className=" cursor-pointer text-3xl text-gray-600 hover:text-emerald-500  transition-all"
                    onClick={() => setDarkMode(!darkMode)}
                  />
                </div>
              ) : (
                <div className="flex items-center">
                  <BsFillSunFill
                    className="cursor-pointer text-3xl text-emerald-500 hover:text-gray-600  transition-all"
                    onClick={() => setDarkMode(!darkMode)}
                  />
                </div>
              )}
            </div>
          </nav>

          <div className="lg:flex lg:justify-between lg:items-end lg:py-10">
            <div>
              <div className=" text-center lg:text-left py-8">
                <p className="text-gray-600 font-medium md:text-xl dark:text-white tracking-in-expand">
                  Hello, i'm
                </p>
                <h2 className=" tracking-in-expand text-5xl py-2 text-emerald-500 font-medium md:text-6xl animate-pulse">
                  Aymeric
                </h2>
                <p className="text-md py-5 px-10 leading-6 text-gray-600 md:text-xl lg:pl-0 lg:max-w-lg dark:text-white fade-in-left">
                  I create responsive web sites with a particular appetite for
                  the user experience. As a junior developer, i'm
                  <span className="text-emerald-500"> persevering</span> and
                  <span className="text-emerald-500"> highly motivated</span>. I
                  like to challenge myself on web development technologies
                </p>
              </div>
              <div className="text-5xl flex justify-center items-center lg:flex lg:justify-start gap-10 py-3 text-gray-600 fade-in-right">
                <a
                  className="text-xl text-center bg-emerald-600 text-white px-4 py-2 border-none rounded-md hover:scale-110 hover:bg-emerald-500 transition-all"
                  href="#"
                >
                  Download my resume
                </a>
                <a
                  href="https://www.linkedin.com/in/di-maggio-aymeric/"
                  target="_blank"
                >
                  <AiFillLinkedin className=" dark:hover:text-slate-300 hover:scale-125 transition" />
                </a>
                <a href="https://github.com/AymericDM83" target="_blank">
                  <AiFillGithub className=" dark:hover:text-slate-300 hover:scale-125 transition " />
                </a>
              </div>
            </div>
            <div className="relative bg-gradient-to-t from-emerald-400 rounded-full w-60 h-60 mt-20 mx-auto overflow-hidden md:h-70 md:w-70 lg:h-80 lg:w-80 lg:mt-0 xl:mx-0 fade-in-left">
              <Image src={aymericPic} layout="fill" objectFit="cover" />
            </div>
          </div>
          <div className="text-5xl flex justify-end items-center py-10 text-emerald-600 sm:mt-10 md:pb-0 md:ml-5 md:text-6xl md:mt-2 lg:justify-center lg:mt-40 lg:text-7xl lg:pt-0">
            <a href="#sectionSkills">
              <BsFillArrowDownCircleFill className="dark:hover:text-slate-300  transition animate-bounce " />
            </a>
          </div>
        </section>

        <section id="sectionSkills" className="py-5">
          <div>
            <h3 className="text-4xl py-1 text-center text-emerald-500 font-medium md:text-6xl">
              My Skills
            </h3>
            <div className="h-2 w-10 bg-emerald-500 rounded-full mx-auto my-10"></div>
          </div>
          <div className="text-center p-7 rounded-xl my-10 flex-1 max-w-2xl mx-auto ">
            <ul className="text-white text-md flex flex-wrap justify-center gap-5 ">
              <li className="p-3 bg-gray-600 rounded-2xl ">CSS</li>
              <li className="p-3 bg-gray-600 rounded-2xl ">HTML</li>
              <li className="p-3 bg-gray-600 rounded-2xl ">JavaScript</li>
              <li className="p-3 bg-gray-600 rounded-2xl ">ReactJS</li>
              <li className="p-3 bg-gray-600 rounded-2xl ">Sass</li>
              <li className="p-3 bg-gray-600 rounded-2xl ">Tailwind CSS</li>
              <li className="p-3 bg-gray-600 rounded-2xl ">SEO</li>
              <li className="p-3 bg-gray-600 rounded-2xl ">Git</li>
              <li className="p-3 bg-gray-600 rounded-2xl ">
                Responsive Design
              </li>
              <li className="p-3 bg-gray-600 rounded-2xl ">API REST</li>
              <li className="p-3 bg-gray-600 rounded-2xl ">NodeJs Basics</li>
              <li className="p-3 bg-gray-600 rounded-2xl ">Express Basics</li>
              <li className="p-3 bg-gray-600 rounded-2xl ">MongoDB</li>
              <li className="p-3 bg-gray-600 rounded-2xl ">Mongoose</li>
            </ul>
          </div>
        </section>

        <section id="sectionProjects" className="py-5">
          <div>
            <h3 className="text-4xl py-1 text-center text-emerald-500 font-medium md:text-6xl">
              My Projects
            </h3>
            <div className="h-2 w-10 bg-emerald-500 rounded-full mx-auto my-10"></div>
          </div>
          <div
            id="Card__Container"
            className="flex-row items-center lg:flex lg:justify-around lg:gap-10"
          >
            <div className="dark:text-white dark:bg-gray-800 bg-gray-200 rounded-xl max-w-lg mx-auto my-10 hover:-translate-y-2 transition-all">
              <div className="lg:flex-row lg:flex-wrap ">
                <div className="text-center p-3 rounded-xl">
                  <Image
                    src={kasaPic}
                    width={500}
                    height={350}
                    className="rounded-xl p-5"
                  />
                  <h3 className="text-lg font-medium pt-4 pb-1">Kasa</h3>
                  <p className="py-1 px-3">
                    Responsive lodging reservations website with ReactJS / Sass
                  </p>
                  <div></div>
                  <ul className="text-white text-md flex flex-wrap justify-center gap-5 p-3">
                    <li className="p-2 dark:bg-gray-700 dark:text-white rounded-2xl bg-gray-300 text-gray-600 ">
                      HTML
                    </li>
                    <li className="p-2 dark:bg-gray-700 dark:text-white rounded-2xl bg-gray-300 text-gray-600 ">
                      JavaScript
                    </li>
                    <li className="p-2 dark:bg-gray-700 dark:text-white rounded-2xl bg-gray-300 text-gray-600 ">
                      ReactJS
                    </li>
                    <li className="p-2 dark:bg-gray-700 dark:text-white rounded-2xl bg-gray-300 text-gray-600 ">
                      Sass
                    </li>
                    <li className="p-2 dark:bg-gray-700 dark:text-white rounded-2xl bg-gray-300 text-gray-600 ">
                      Git
                    </li>
                    <li className="p-2 dark:bg-gray-700 dark:text-white rounded-2xl bg-gray-300 text-gray-600 ">
                      Responsive Design
                    </li>
                  </ul>
                  <div className="flex justify-center items-center gap-20 py-5 dark:hover:text-white">
                    <a
                      href="https://github.com/AymericDM83/Kasa-P7-OpenClassrooms"
                      className="text-xl text-center text-white px-4 py-2 border-none rounded-md hover:-translate-y-1  bg-emerald-500 hover:bg-emerald-400 transition-all "
                    >
                      {" "}
                      <p className="text-white dark:hover:text-white">
                        Source Code
                      </p>{" "}
                    </a>
                    <a
                      href="https://aymericdm83.github.io/Kasa-P7-OpenClassrooms/"
                      className="text-xl text-center text-white px-4 py-2 border-none rounded-md hover:-translate-y-1 bg-emerald-500 hover:bg-emerald-400 transition-all"
                    >
                      {" "}
                      <p className="text-white ">Live website</p>{" "}
                    </a>
                  </div>
                </div>
              </div>
            </div>

            <div className="dark:text-white dark:bg-gray-800 bg-gray-200 rounded-xl max-w-lg mx-auto my-10 hover:-translate-y-2 transition-all">
              <div className="lg:flex-row lg:flex-wrap ">
                <div className="text-center p-3 rounded-xl">
                  <Image
                    src={kasaPic}
                    width={500}
                    height={350}
                    className="rounded-xl p-5"
                  />
                  <h3 className="text-lg font-medium pt-4 pb-1">Kasa</h3>
                  <p className="py-1 px-3">
                    Responsive lodging reservations website with ReactJS / Sass
                  </p>
                  <div></div>
                  <ul className="text-white text-md flex flex-wrap justify-center gap-5 p-3">
                    <li className="p-2 dark:text-white dark:bg-gray-700 rounded-2xl bg-gray-300 text-gray-600">
                      HTML
                    </li>
                    <li className="p-2 dark:text-white dark:bg-gray-700 rounded-2xl bg-gray-300 text-gray-600">
                      JavaScript
                    </li>
                    <li className="p-2 dark:text-white dark:bg-gray-700 rounded-2xl bg-gray-300 text-gray-600">
                      ReactJS
                    </li>
                    <li className="p-2 dark:text-white dark:bg-gray-700 rounded-2xl bg-gray-300 text-gray-600">
                      Sass
                    </li>
                    <li className="p-2 dark:text-white dark:bg-gray-700 rounded-2xl bg-gray-300 text-gray-600">
                      Git
                    </li>
                    <li className="p-2 dark:text-white dark:bg-gray-700 rounded-2xl bg-gray-300 text-gray-600">
                      Responsive Design
                    </li>
                  </ul>
                  <div className="flex justify-center items-center gap-20 py-5 dark:hover:text-white">
                    <a
                      href="https://github.com/AymericDM83/Kasa-P7-OpenClassrooms"
                      className="text-xl text-center text-white px-4 py-2 border-none rounded-md hover:-translate-y-1  bg-emerald-500 hover:bg-emerald-400 transition-all "
                    >
                      {" "}
                      <p className="text-white dark:hover:text-white">
                        Source Code
                      </p>{" "}
                    </a>
                    <a
                      href="https://aymericdm83.github.io/Kasa-P7-OpenClassrooms/"
                      className="text-xl text-center text-white px-4 py-2 border-none rounded-md hover:-translate-y-1 bg-emerald-500 hover:bg-emerald-400 transition-all"
                    >
                      {" "}
                      <p className="text-white ">Live website</p>{" "}
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
